// Code generated by github.com/go-leo/sqlgen. DO NOT EDIT.
// Code generated by github.com/go-leo/sqlgen. DO NOT EDIT.
// Code generated by github.com/go-leo/sqlgen. DO NOT EDIT.

package entity

const TableNameNewMediaBook = "new_media_book"

// NewMediaBook mapped from table <new_media_book>
type NewMediaBook struct {
	ID                     int64  `gorm:"column:id;not null" json:"id"`                                                    // 自增ID
	OrigID                 int64  `gorm:"column:orig_id;not null" json:"orig_id"`                                          // 原始书籍ID
	Title                  string `gorm:"column:title" json:"title"`                                                       // 新媒体书名
	CoverPath              string `gorm:"column:cover_path;not null" json:"cover_path"`                                    // 新媒体封面
	AuthorID               int32  `gorm:"column:author_id;not null" json:"author_id"`                                      // 作者ID
	AuthorName             string `gorm:"column:author_name;not null" json:"author_name"`                                  // 小说作者
	Summary                string `gorm:"column:summary;not null" json:"summary"`                                          // 新媒体书籍简介
	Category1ID            int32  `gorm:"column:category1_id;not null" json:"category1_id"`                                // 一级分类ID
	Category2ID            int32  `gorm:"column:category2_id;not null" json:"category2_id"`                                // 二级分类ID
	IsOver                 int8   `gorm:"column:is_over;not null" json:"is_over"`                                          // 是否完结（0连载，1完结,2断更）
	Words                  int64  `gorm:"column:words;not null" json:"words"`                                              // 新媒体书籍字数
	Characters             string `gorm:"column:characters" json:"characters"`                                             // 新媒体主角名
	FirstPaidChapterNum    int32  `gorm:"column:first_paid_chapter_num;not null;default:10" json:"first_paid_chapter_num"` // 新媒体起始付费章节数
	Price                  int64  `gorm:"column:price;not null;default:59" json:"price"`                                   // 新媒体书籍价格。单位：分
	PriceType              int8   `gorm:"column:price_type;not null" json:"price_type"`                                    // 定价类型：0 千字定价，1 章节定价
	LatestChapterID        string `gorm:"column:latest_chapter_id;not null" json:"latest_chapter_id"`                      // 新媒体最后更新章节ID
	LatestChapterTitle     string `gorm:"column:latest_chapter_title;not null" json:"latest_chapter_title"`                // 新媒体最后章节名称
	SevendayReadingCount   int64  `gorm:"column:sevenday_reading_count;not null" json:"sevenday_reading_count"`
	WxSevendayReadingCount int64  `gorm:"column:wx_sevenday_reading_count;not null" json:"wx_sevenday_reading_count"` // 新媒体微信公众号7日阅读量
	Status                 int8   `gorm:"column:status;not null" json:"status"`                                       // 新媒体书籍状态：0待上架架，1上架，2 下架
}

// TableName NewMediaBook's table name
func (*NewMediaBook) TableName() string {
	return TableNameNewMediaBook
}
