// Code generated by github.com/go-leo/sqlgen. DO NOT EDIT.
// Code generated by github.com/go-leo/sqlgen. DO NOT EDIT.
// Code generated by github.com/go-leo/sqlgen. DO NOT EDIT.

package entity

import (
	"time"
)

const TableNameUserFeedback = "user_feedback"

// UserFeedback mapped from table <user_feedback>
type UserFeedback struct {
	ID               int64     `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	UID              int64     `gorm:"column:uid;not null" json:"uid"`
	Project          string    `gorm:"column:project;not null" json:"project"`
	Appid            string    `gorm:"column:appid;not null" json:"appid"`     // appid
	Channel          string    `gorm:"column:channel;not null" json:"channel"` // 渠道
	FeedBack         string    `gorm:"column:feed_back;not null" json:"feed_back"`
	ContactDetails   string    `gorm:"column:contact_details" json:"contact_details"`
	AppVersion       string    `gorm:"column:app_version;not null" json:"app_version"`                                         // 应用版本
	PhoneModel       string    `gorm:"column:phone_model;not null" json:"phone_model"`                                         // 手机型号
	PhoneOs          string    `gorm:"column:phone_os;not null" json:"phone_os"`                                               // 手机操作系统
	Status           int8      `gorm:"column:status;not null" json:"status"`                                                   // 处理状态：0 未处理；1 跟进中；2 已处理；3 无需处理
	ReplyStatus      int8      `gorm:"column:reply_status;not null" json:"reply_status"`                                       // 回复状态：0 未回复；1 已回复
	LastAdminID      int64     `gorm:"column:last_admin_id" json:"last_admin_id"`                                              // 最近处理人ID
	Remark           string    `gorm:"column:remark" json:"remark"`                                                            // 处理备注
	FrameworkVersion string    `gorm:"column:framework_version;not null" json:"framework_version"`                             // 快应用-框架版本、公众号-微信版本
	Resolution       string    `gorm:"column:resolution;not null" json:"resolution"`                                           // 分辨率
	LastMessageID    int64     `gorm:"column:last_message_id" json:"last_message_id"`                                          // 最后的消息id
	LastFeedbackTime time.Time `gorm:"column:last_feedback_time;not null;default:CURRENT_TIMESTAMP" json:"last_feedback_time"` // 用户最后反馈的时间
	FirstReplyTime   time.Time `gorm:"column:first_reply_time" json:"first_reply_time"`                                        // 首次回复时间
	LastReplyTime    time.Time `gorm:"column:last_reply_time" json:"last_reply_time"`                                          // 最近回复时间
	CreateTime       time.Time `gorm:"column:create_time" json:"create_time"`
	UpdateTime       time.Time `gorm:"column:update_time" json:"update_time"`
}

// TableName UserFeedback's table name
func (*UserFeedback) TableName() string {
	return TableNameUserFeedback
}
