// Code generated by github.com/go-leo/sqlgen. DO NOT EDIT.
// Code generated by github.com/go-leo/sqlgen. DO NOT EDIT.
// Code generated by github.com/go-leo/sqlgen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"gorm.io/gorm"

	"github.com/go-leo/sqlgen"

	"gorm.io/plugin/dbresolver"
)

func Use(db *gorm.DB, opts ...sqlgen.DOOption) *Query {
	return &Query{
		db:              db,
		feedbackMessage: newFeedbackMessage(db, opts...),
		userFeedback:    newUserFeedback(db, opts...),
	}
}

type Query struct {
	db *gorm.DB

	feedbackMessage feedbackMessage
	userFeedback    userFeedback
}

func (q *Query) Available() bool { return q.db != nil }

func (q *Query) clone(db *gorm.DB) *Query {
	return &Query{
		db:              db,
		feedbackMessage: q.feedbackMessage.clone(db),
		userFeedback:    q.userFeedback.clone(db),
	}
}

func (q *Query) ReadDB() *Query {
	return q.clone(q.db.Clauses(dbresolver.Read))
}

func (q *Query) WriteDB() *Query {
	return q.clone(q.db.Clauses(dbresolver.Write))
}

func (q *Query) ReplaceDB(db *gorm.DB) *Query {
	return &Query{
		db:              db,
		feedbackMessage: q.feedbackMessage.replaceDB(db),
		userFeedback:    q.userFeedback.replaceDB(db),
	}
}

type queryInstance struct {
	FeedbackMessage feedbackMessage
	UserFeedback    userFeedback
}

func (q *Query) Instance(ctx context.Context) *queryInstance {
	tx, ok := ctx.Value(contextTxKey{}).(*gorm.DB)
	if ok {
		new := q.clone(tx)
		return &queryInstance{
			FeedbackMessage: new.feedbackMessage,
			UserFeedback:    new.userFeedback,
		}
	}
	return &queryInstance{
		FeedbackMessage: q.feedbackMessage,
		UserFeedback:    q.userFeedback,
	}
}

type queryDo struct {
	FeedbackMessage *feedbackMessageDo
	UserFeedback    *userFeedbackDo
}

func (q *queryInstance) WithContext(ctx context.Context) *queryDo {
	return &queryDo{
		FeedbackMessage: q.FeedbackMessage.WithContext(ctx),
		UserFeedback:    q.UserFeedback.WithContext(ctx),
	}
}

// 用来承载事务的上下文
type contextTxKey struct{}

func (q *Query) ExecTx(ctx context.Context, f func(ctx context.Context) error) error {
	return q.db.WithContext(ctx).Transaction(func(tx *gorm.DB) error {
		ctx := context.WithValue(ctx, contextTxKey{}, tx)
		return f(ctx)
	})
}

func (q *Query) Transaction(fc func(tx *Query) error, opts ...*sql.TxOptions) error {
	return q.db.Transaction(func(tx *gorm.DB) error { return fc(q.clone(tx)) }, opts...)
}

func (q *Query) Begin(opts ...*sql.TxOptions) *QueryTx {
	return &QueryTx{q.clone(q.db.Begin(opts...))}
}

type QueryTx struct{ *Query }

func (q *QueryTx) Commit() error {
	return q.db.Commit().Error
}

func (q *QueryTx) Rollback() error {
	return q.db.Rollback().Error
}

func (q *QueryTx) SavePoint(name string) error {
	return q.db.SavePoint(name).Error
}

func (q *QueryTx) RollbackTo(name string) error {
	return q.db.RollbackTo(name).Error
}
